name: Push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: quike/action-semantic-release@v1.0.1
        with:
          token: ${{ secrets.GHTOKEN }}
          debug-mode: true
          dry-run: false
          default-config-enabled: true
